version: "3.2"
services:
  apache:
    container_name: php72
    image: chandra9853/imprintnext-php-localenviromnent:latest
    depends_on:
     - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
        - ./public_html/:/var/www/html/
        - ./vhosts/000-default.conf:/etc/apache2/sites-available/000-default.conf
    #command: bash -c "sleep 20 && cp -a /var/www/html/xeprojects/. /var/xeprojects"
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
  phpmyadmin:
     container_name: inkxe10_phpmyadmin
     depends_on:
      - mysql
     image: phpmyadmin/phpmyadmin
     restart: always
     networks:
      - frontend
      - backend
     ports:
      - 8080:80
     environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 'root'
networks:
  frontend:
  backend:
volumes:
    db_data: {}
